DROP DATABASE lab_mysql;
CREATE DATABASE lab_mysql;
USE lab_mysql;
 CREATE TABLE IF NOT EXISTS MAIN
(DeporteID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
Deporte VARCHAR(25),
 Jugadores INT(2) ,
 Equipos INT(2),
 Liga VARCHAR(25),
 Cualidad1 VARCHAR(25),
 Cualidad2 VARCHAR(25));
 CREATE TABLE IF NOT EXISTS JUGADORES
 (EquiposID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 Jugador VARCHAR(40) NOT NULL,
 Apellido VARCHAR(40) NOT NULL,
 Equipo VARCHAR(40) NOT NULL,
 Liga VARCHAR(40)NOT NULL,
 Pais VARCHAR(40) NOT NULL);
 CREATE TABLE IF NOT EXISTS CUALIDADES
 (Deporte VARCHAR(40) NOT NULL,
 Duracion_Por_Tiempo BOOLEAN,
 Duracion_Por_Juego BOOLEAN NOT NULL,
 Tiempo_Extra BOOLEAN NOT NULL);