CREATE DATABASE lab_mysql;
USE lab_mysql;
CREATE TABLE Cars(VIN varchar(50) primary key, Manufacturer varchar(30), Model varchar(40), year_ year, color varchar(20));
CREATE TABLE Stores(Store_ID varchar(80) primary key, Address varchar(80),City varchar(35),Country varchar(35),ZIP int);
CREATE TABLE Salespersons(Salesperson_ID int primary key, Name_ varchar(80), Store_ID varchar(80), foreign key(Store_ID) references Stores(Store_ID));
CREATE TABLE Customers(Customers_ID int primary key, Name_ varchar(80), Phone_number int ,email varchar(50), Address varchar(80),City varchar(35),Country varchar(35),ZIP int);
CREATE TABLE Invoices(Invoice_number int primary key, Date_ year, VIN varchar(50), foreign key(VIN) references Cars(VIN), Customers_ID int, foreign key(Customers_ID) references Customers(Customers_ID),Salesperson_ID int, foreign key(Salesperson_ID) references Salespersons(Salesperson_ID));
INSERT INTO Cars values ('3K096I98581DHSNUP','Volkswagen','Tiguan',2019,'Blue');
INSERT INTO Cars values ('RKXVNNIHLVVZOUB4M','Ford','Fusion',2018,'White');
INSERT INTO Cars values ('HKNDGS7CU31E9Z7JW','Toyota','RAV4',2018,'Silver');
INSERT INTO Cars values ('DAM41UDN3CHU2WVF6','Volvo','V60',2019,'Gray');
INSERT INTO Stores values(0,'Tacubaya','CDMX','México',00000);
INSERT INTO Stores values(1,'Reforma','CDMX','México',00001);
INSERT INTO Stores values(2,'Santafé','CDMX','México',00002);
INSERT INTO Stores values(3,'Reforma2','CDMX','México',00003);
INSERT INTO Customers values(0,'Juan',55555111,'juanito@gmail.com','Reforma','CDMX','México',00001);
INSERT INTO Customers values (1,'Abraham',55555222,'Abraham@gmail.com','Condesa','CDMX','México',33130);
INSERT INTO Customers values (2,'Napoléon',55555333,'superbarrio@gmail.com','Tepito','CDMX','México',75008);
INSERT INTO Salespersons values (0,'Rosa',0);
INSERT INTO Salespersons values (1,'Rodrigo',1);
INSERT INTO Salespersons values (2,'Raúl',2);
INSERT INTO Invoices values(0,2019,'3K096I98581DHSNUP',0,1);
INSERT INTO Invoices values(1,2019,'RKXVNNIHLVVZOUB4M',1,0);
INSERT INTO Invoices values(2,2019,'DAM41UDN3CHU2WVF6',2,1);